const Student_Action_type = {
    FETCH_ALL_STUDENTS : 'FETCH_ALL_STUDENTS',
    FETCH_SINGLE_STUDENT : 'FETCH_SINGLE_STUDENT',
    FETCH_INSERT_STUDENT : 'FETCH_INSERT_STUDENT',
    FETCH_EDIT_STUDENT : 'FETCH_EDIT_STUDENT',
    FETCH_ENROLL_STUDENT : 'FETCH_ENROLL_STUDENT',
    FETCH_DELETE_STUDENT : 'FETCH_DELETE_STUDENT'
};

export default Student_Action_type;